// Declare DOM objects
const loanAmount = document.querySelector(".loan-amount");
const interest = document.querySelector(".interest");
const years = document.querySelector(".years");
const calcBtn = document.querySelector(".calc");
const calculating = document.querySelector("#calculating");
const results = document.querySelector(".results");
const monthlyPayment = document.querySelector(".monthly-payment");
const totalPayment = document.querySelector(".total-payment");
const totalInterest = document.querySelector(".total-interest");
